nav:
- Go packages:
  - github.com/snyk/vervet/v4: github.com/snyk/vervet/v4.md
  - github.com/snyk/vervet/v4/config: github.com/snyk/vervet/v4/config.md
  - github.com/snyk/vervet/v4/versionware: github.com/snyk/vervet/v4/versionware.md
plugins:
- techdocs-core
site_name: vervet
