version: "3.8"

services:
  # https://github.com/fsouza/fake-gcs-server
  fake-gcs:
    image: fsouza/fake-gcs-server
    command:
      - "-scheme"
      - "http"
      - "-backend"
      - "memory"
      - "-port"
      - "4443"
      - "-public-host"
      - "localhost:4443"
      - "-data"
      - "/data"
    ports:
      - "4443:4443"
    volumes:
      - "${TMPDIR:-/tmp}/data:/data"
  localstack:
    image: localstack/localstack:0.13.3
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - MAIN_CONTAINER_NAME=localstack
      - EDGE_PORT=4566
      - SERVICES=${SERVICES:- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  vervet-underground:
    build:
      context: ./
      dockerfile: Dockerfile
    image: vervet-underground
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/${CONFIG:-config.json}:/config.default.json
